package client.network;

public enum State {
    WAIT,
    SETUPFIRST,
    SETUP,
    WAITINGINLOBBY,
    SETTINGNICKNAME,
    SETTINGNEWLOBBY,
    INQUEUE,
    SETTINGPLAYERSNUMBER,
    WAITINGFORMYTURN,
    MYTURN,
    WAITINGFORRESPONSE,
    WAITINGFORGAMESTART,
    PLAYERSQUIT,
    GAMEENDED
}