package client.network;

public enum State {
    WAIT,
    WAITINGINLOBBY,
    SETTINGNICKNAME,
    SETTINGPLAYERSNUMBER,
    WAITINGFORMYTURN,
    MYTURN,
    WAITINGFORRESPONSE,
    WAITINGFORGAMESTART,
    PLAYERSQUIT,
    GAMEENDED

}